apiVersion: v1
kind: Pod
metadata:
  name: nccoffee
  labels:
    app: nccoffee
spec:
  containers:
  - image: thenetworkchuck/nccoffee:pourover
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nccoffee
spec:
  selector:
    app: nccoffee
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nccoffee
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nccoffee
          servicePort: 80